{
  "swagger": "2.0",
  "info": {
    "title": "DIPs API",
    "description": "The DIPs API is used to request DIP creation and retrieve DIP details.",
    "version": "0.1.0"
  },
  "host": "localhost:80",
  "consumes": [
    "application/json",
    "application/xml",
    "application/gob"
  ],
  "produces": [
    "application/json",
    "application/xml",
    "application/gob"
  ],
  "paths": {
    "/dips": {
      "post": {
        "tags": [
          "DIPs"
        ],
        "summary": "create DIPs",
        "description": "The create method requests DIP creation for a document key.",
        "operationId": "DIPs#create",
        "parameters": [
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "docKey": {
                  "type": "string",
                  "description": "The docKey field contains the document key used to create the DIP.",
                  "example": "CH-000001",
                  "minLength": 1
                }
              }
            }
          }
        ],
        "responses": {
          "202": {
            "description": "Accepted response.",
            "schema": {
              "$ref": "#/definitions/DIPsCreateResponseBody",
              "required": [
                "id"
              ]
            }
          },
          "400": {
            "description": "Bad Request response.",
            "schema": {
              "$ref": "#/definitions/DIPsCreateBadRequestResponseBody"
            }
          },
          "401": {
            "description": "Unauthorized response.",
            "schema": {
              "$ref": "#/definitions/DIPsCreateUnauthorizedResponseBody"
            }
          },
          "500": {
            "description": "Internal Server Error response.",
            "schema": {
              "$ref": "#/definitions/DIPsCreateInternalServerErrorResponseBody"
            }
          }
        },
        "schemes": [
          "http"
        ],
        "security": [
          {
            "bearer_header_Authorization": null
          }
        ]
      }
    },
    "/dips/{id}": {
      "get": {
        "tags": [
          "DIPs"
        ],
        "summary": "show DIPs",
        "description": "The show method retrieves DIP details.",
        "operationId": "DIPs#show",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "DIPID uniquely identifies a DIP.",
            "required": true,
            "type": "string",
            "format": "uuid"
          }
        ],
        "responses": {
          "200": {
            "description": "OK response.",
            "schema": {
              "$ref": "#/definitions/DIPsShowResponseBody",
              "required": [
                "id",
                "docKey",
                "status",
                "created_at"
              ]
            }
          },
          "400": {
            "description": "Bad Request response.",
            "schema": {
              "$ref": "#/definitions/DIPsShowBadRequestResponseBody"
            }
          },
          "401": {
            "description": "Unauthorized response.",
            "schema": {
              "$ref": "#/definitions/DIPsShowUnauthorizedResponseBody"
            }
          },
          "404": {
            "description": "Not Found response.",
            "schema": {
              "$ref": "#/definitions/DIPsShowNotFoundResponseBody"
            }
          },
          "500": {
            "description": "Internal Server Error response.",
            "schema": {
              "$ref": "#/definitions/DIPsShowInternalServerErrorResponseBody"
            }
          }
        },
        "schemes": [
          "http"
        ],
        "security": [
          {
            "bearer_header_Authorization": null
          }
        ]
      }
    }
  },
  "definitions": {
    "DIPsCreateBadRequestResponseBody": {
      "title": "Mediatype identifier: application/vnd.goa.error; view=default",
      "type": "object",
      "properties": {
        "fault": {
          "type": "boolean",
          "description": "Is the error a server-side fault?",
          "example": true
        },
        "id": {
          "type": "string",
          "description": "ID is a unique identifier for this particular occurrence of the problem.",
          "example": "123abc"
        },
        "message": {
          "type": "string",
          "description": "Message is a human-readable explanation specific to this occurrence of the problem.",
          "example": "parameter 'p' must be an integer"
        },
        "name": {
          "type": "string",
          "description": "Name is the name of this class of errors.",
          "example": "bad_request"
        },
        "temporary": {
          "type": "boolean",
          "description": "Is the error temporary?",
          "example": true
        },
        "timeout": {
          "type": "boolean",
          "description": "Is the error a timeout?",
          "example": true
        }
      },
      "description": "create_bad_request_response_body result type (default view)",
      "example": {
        "fault": true,
        "id": "123abc",
        "message": "parameter 'p' must be an integer",
        "name": "bad_request",
        "temporary": false,
        "timeout": true
      },
      "required": [
        "name",
        "id",
        "message",
        "temporary",
        "timeout",
        "fault"
      ]
    },
    "DIPsCreateInternalServerErrorResponseBody": {
      "title": "Mediatype identifier: application/vnd.goa.error; view=default",
      "type": "object",
      "properties": {
        "fault": {
          "type": "boolean",
          "description": "Is the error a server-side fault?",
          "example": false
        },
        "id": {
          "type": "string",
          "description": "ID is a unique identifier for this particular occurrence of the problem.",
          "example": "123abc"
        },
        "message": {
          "type": "string",
          "description": "Message is a human-readable explanation specific to this occurrence of the problem.",
          "example": "parameter 'p' must be an integer"
        },
        "name": {
          "type": "string",
          "description": "Name is the name of this class of errors.",
          "example": "bad_request"
        },
        "temporary": {
          "type": "boolean",
          "description": "Is the error temporary?",
          "example": false
        },
        "timeout": {
          "type": "boolean",
          "description": "Is the error a timeout?",
          "example": true
        }
      },
      "description": "create_internal_server_error_response_body result type (default view)",
      "example": {
        "fault": true,
        "id": "123abc",
        "message": "parameter 'p' must be an integer",
        "name": "bad_request",
        "temporary": true,
        "timeout": false
      },
      "required": [
        "name",
        "id",
        "message",
        "temporary",
        "timeout",
        "fault"
      ]
    },
    "DIPsCreateResponseBody": {
      "title": "DIPsCreateResponseBody",
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "The id field contains the identifier assigned to the DIP.",
          "example": "3f38d6f4-7b19-4db8-8d7d-693b84a9a2fb",
          "format": "uuid"
        }
      },
      "example": {
        "id": "3f38d6f4-7b19-4db8-8d7d-693b84a9a2fb"
      },
      "required": [
        "id"
      ]
    },
    "DIPsCreateUnauthorizedResponseBody": {
      "title": "Mediatype identifier: application/vnd.goa.error; view=default",
      "type": "object",
      "properties": {
        "fault": {
          "type": "boolean",
          "description": "Is the error a server-side fault?",
          "example": true
        },
        "id": {
          "type": "string",
          "description": "ID is a unique identifier for this particular occurrence of the problem.",
          "example": "123abc"
        },
        "message": {
          "type": "string",
          "description": "Message is a human-readable explanation specific to this occurrence of the problem.",
          "example": "parameter 'p' must be an integer"
        },
        "name": {
          "type": "string",
          "description": "Name is the name of this class of errors.",
          "example": "bad_request"
        },
        "temporary": {
          "type": "boolean",
          "description": "Is the error temporary?",
          "example": false
        },
        "timeout": {
          "type": "boolean",
          "description": "Is the error a timeout?",
          "example": true
        }
      },
      "description": "create_unauthorized_response_body result type (default view)",
      "example": {
        "fault": false,
        "id": "123abc",
        "message": "parameter 'p' must be an integer",
        "name": "bad_request",
        "temporary": true,
        "timeout": true
      },
      "required": [
        "name",
        "id",
        "message",
        "temporary",
        "timeout",
        "fault"
      ]
    },
    "DIPsShowBadRequestResponseBody": {
      "title": "Mediatype identifier: application/vnd.goa.error; view=default",
      "type": "object",
      "properties": {
        "fault": {
          "type": "boolean",
          "description": "Is the error a server-side fault?",
          "example": false
        },
        "id": {
          "type": "string",
          "description": "ID is a unique identifier for this particular occurrence of the problem.",
          "example": "123abc"
        },
        "message": {
          "type": "string",
          "description": "Message is a human-readable explanation specific to this occurrence of the problem.",
          "example": "parameter 'p' must be an integer"
        },
        "name": {
          "type": "string",
          "description": "Name is the name of this class of errors.",
          "example": "bad_request"
        },
        "temporary": {
          "type": "boolean",
          "description": "Is the error temporary?",
          "example": true
        },
        "timeout": {
          "type": "boolean",
          "description": "Is the error a timeout?",
          "example": true
        }
      },
      "description": "show_bad_request_response_body result type (default view)",
      "example": {
        "fault": true,
        "id": "123abc",
        "message": "parameter 'p' must be an integer",
        "name": "bad_request",
        "temporary": false,
        "timeout": false
      },
      "required": [
        "name",
        "id",
        "message",
        "temporary",
        "timeout",
        "fault"
      ]
    },
    "DIPsShowInternalServerErrorResponseBody": {
      "title": "Mediatype identifier: application/vnd.goa.error; view=default",
      "type": "object",
      "properties": {
        "fault": {
          "type": "boolean",
          "description": "Is the error a server-side fault?",
          "example": true
        },
        "id": {
          "type": "string",
          "description": "ID is a unique identifier for this particular occurrence of the problem.",
          "example": "123abc"
        },
        "message": {
          "type": "string",
          "description": "Message is a human-readable explanation specific to this occurrence of the problem.",
          "example": "parameter 'p' must be an integer"
        },
        "name": {
          "type": "string",
          "description": "Name is the name of this class of errors.",
          "example": "bad_request"
        },
        "temporary": {
          "type": "boolean",
          "description": "Is the error temporary?",
          "example": false
        },
        "timeout": {
          "type": "boolean",
          "description": "Is the error a timeout?",
          "example": false
        }
      },
      "description": "show_internal_server_error_response_body result type (default view)",
      "example": {
        "fault": false,
        "id": "123abc",
        "message": "parameter 'p' must be an integer",
        "name": "bad_request",
        "temporary": true,
        "timeout": false
      },
      "required": [
        "name",
        "id",
        "message",
        "temporary",
        "timeout",
        "fault"
      ]
    },
    "DIPsShowNotFoundResponseBody": {
      "title": "Mediatype identifier: application/vnd.goa.error; view=default",
      "type": "object",
      "properties": {
        "fault": {
          "type": "boolean",
          "description": "Is the error a server-side fault?",
          "example": false
        },
        "id": {
          "type": "string",
          "description": "ID is a unique identifier for this particular occurrence of the problem.",
          "example": "123abc"
        },
        "message": {
          "type": "string",
          "description": "Message is a human-readable explanation specific to this occurrence of the problem.",
          "example": "parameter 'p' must be an integer"
        },
        "name": {
          "type": "string",
          "description": "Name is the name of this class of errors.",
          "example": "bad_request"
        },
        "temporary": {
          "type": "boolean",
          "description": "Is the error temporary?",
          "example": true
        },
        "timeout": {
          "type": "boolean",
          "description": "Is the error a timeout?",
          "example": true
        }
      },
      "description": "show_not_found_response_body result type (default view)",
      "example": {
        "fault": false,
        "id": "123abc",
        "message": "parameter 'p' must be an integer",
        "name": "bad_request",
        "temporary": true,
        "timeout": false
      },
      "required": [
        "name",
        "id",
        "message",
        "temporary",
        "timeout",
        "fault"
      ]
    },
    "DIPsShowResponseBody": {
      "title": "DIPsShowResponseBody",
      "type": "object",
      "properties": {
        "completed_at": {
          "type": "string",
          "description": "The completed_at field contains the time when DIP processing completed.",
          "example": "2026-05-27T15:04:05Z",
          "format": "date-time"
        },
        "created_at": {
          "type": "string",
          "description": "The created_at field contains the time when the DIP was requested.",
          "example": "2026-05-27T15:04:05Z",
          "format": "date-time"
        },
        "docKey": {
          "type": "string",
          "description": "The docKey field contains the document key used to create the DIP.",
          "example": "CH-000001",
          "minLength": 1
        },
        "id": {
          "type": "string",
          "description": "The id field uniquely identifies the DIP.",
          "example": "3f38d6f4-7b19-4db8-8d7d-693b84a9a2fb",
          "format": "uuid"
        },
        "object_key": {
          "type": "string",
          "description": "The object_key field contains the object store key for the completed DIP.",
          "example": "dips/3f38d6f4-7b19-4db8-8d7d-693b84a9a2fb.zip",
          "minLength": 1
        },
        "started_at": {
          "type": "string",
          "description": "The started_at field contains the time when DIP processing started.",
          "example": "2026-05-27T15:04:05Z",
          "format": "date-time"
        },
        "status": {
          "type": "string",
          "description": "The status field contains the current DIP status.",
          "example": "done",
          "enum": [
            "queued",
            "in progress",
            "done",
            "failed"
          ]
        }
      },
      "example": {
        "completed_at": "2026-05-27T15:04:05Z",
        "created_at": "2026-05-27T15:04:05Z",
        "docKey": "CH-000001",
        "id": "3f38d6f4-7b19-4db8-8d7d-693b84a9a2fb",
        "object_key": "dips/3f38d6f4-7b19-4db8-8d7d-693b84a9a2fb.zip",
        "started_at": "2026-05-27T15:04:05Z",
        "status": "done"
      },
      "required": [
        "id",
        "docKey",
        "status",
        "created_at"
      ]
    },
    "DIPsShowUnauthorizedResponseBody": {
      "title": "Mediatype identifier: application/vnd.goa.error; view=default",
      "type": "object",
      "properties": {
        "fault": {
          "type": "boolean",
          "description": "Is the error a server-side fault?",
          "example": false
        },
        "id": {
          "type": "string",
          "description": "ID is a unique identifier for this particular occurrence of the problem.",
          "example": "123abc"
        },
        "message": {
          "type": "string",
          "description": "Message is a human-readable explanation specific to this occurrence of the problem.",
          "example": "parameter 'p' must be an integer"
        },
        "name": {
          "type": "string",
          "description": "Name is the name of this class of errors.",
          "example": "bad_request"
        },
        "temporary": {
          "type": "boolean",
          "description": "Is the error temporary?",
          "example": false
        },
        "timeout": {
          "type": "boolean",
          "description": "Is the error a timeout?",
          "example": false
        }
      },
      "description": "show_unauthorized_response_body result type (default view)",
      "example": {
        "fault": false,
        "id": "123abc",
        "message": "parameter 'p' must be an integer",
        "name": "bad_request",
        "temporary": false,
        "timeout": true
      },
      "required": [
        "name",
        "id",
        "message",
        "temporary",
        "timeout",
        "fault"
      ]
    }
  },
  "securityDefinitions": {
    "bearer_header_Authorization": {
      "type": "apiKey",
      "description": "Authenticate with an access token supplied as Authorization: Bearer [token]. Clients obtain tokens from an external OIDC provider.",
      "name": "Authorization",
      "in": "header"
    }
  }
}
